version: '3'
services:
  mongo:
    image: mongo:3
    container_name: mongo-container
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build:
      context: .
      dockerfile: Dockerfile
    image: clean-architecture-study
    restart: always
    command: npm run debug
    volumes:
      - ./dist:/usr/src/clean-architecture-study/dist
      - ./package.json:/usr/src/clean-architecture-study/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo
    
    
