version: '3'
services:
  mongo:
    image: mongo:3
    container_name: mongo-container
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:17.8.0
    working_dir: /usr/src/clean-architecture-study
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    volumes:
      - ./dist/:/usr/src/clean-architecture-study/dist
      - ./package.json:/usr/src/clean-architecture-study/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo
    
    
